#####################################################################
# File: Proxmox_homeLab_v3/modules/desktop_cli_setup/roles/git_setup/tasks/main.yml
# Purpose: Configure Git settings for the user
# Version: 0.0.1
#####################################################################

---
- name: Configure Git user name
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: Configure Git user email
  community.general.git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global

- name: Set default branch to main
  community.general.git_config:
    name: init.defaultBranch
    value: main
    scope: global

- name: Set pull.rebase to false
  community.general.git_config:
    name: pull.rebase
    value: "false"
    scope: global

- name: Set credential helper to store
  community.general.git_config:
    name: credential.helper
    value: store
    scope: global

- name: Set default editor to nano
  community.general.git_config:
    name: core.editor
    value: nano
    scope: global
