#####################################################################
# File: Proxmox_homeLab_v3/modules/desktop_cli_setup/roles/tools/tasks/main.yml
# Purpose: Install essential tools for the desktop CLI setup
# Version: 0.0.1
#####################################################################

---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install essential tools
  ansible.builtin.apt:
    name:
      - git
      - curl
      - jq
      - whiptail
      - dialog
      - unzip
      - gpg
      - sshpass
      - wget
      - gnupg
      - software-properties-common
      - lsb-release
      - gh
      - python3
      - python3-pip
      - python3-venv
      - make
      - htop
      - ncdu
      - net-tools
      - bat
      - ripgrep
      - fzf
      - tmux
      - neofetch
      - apt-transport-https
    state: present

- name: Install latest yq
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '0755'
